name: Build Releases

on:
  workflow_dispatch:
    inputs:
      steamworks_sdk_tag:
        description: 'Steamworks SDK Github tag:'
        required: true
        type: string
        default: 'sdk-1.59'
      godot_tag:
        description: 'Godot Github tag:'
        required: true
        type: string
        default: '4.2.1-stable'
      godotsteam_version:
        description: 'GodotSteam MP version:'
        required: true
        type: string
        default: '4.6-mp'
      mono_tag:
        description: 'Mono tag:'
        required: true
        type: string
        default: 'release-5299efd'


jobs:
  env-setup:
    uses: ./.github/workflows/setup-env.yml
    with:
      godot_tag: ${{ inputs.godot_tag }}
      godotsteam_version: ${{ inputs.godotsteam_version }}
      steamworks_sdk_tag: ${{ inputs.steamworks_sdk_tag }}

  build-linux:
    needs: [env-setup]
    uses: ./.github/workflows/build-linux-artifact.yml
    with:
      godot_tag: ${{ inputs.godot_tag }}
      mono_tag: ${{ inputs.mono_tag }}
      steamworks_sdk_tag: ${{ inputs.steamworks_sdk_tag }}
    secrets:
      steamworks_sdk_repo: ${{ secrets.STEAMWORKS_SDK_REPO }}
      steamworks_sdk_repo_token: ${{ secrets.STEAMWORKS_SDK_REPO_TOKEN }}

  create-linux-bundle:
    needs: [env-setup, build-linux]
    uses: ./.github/workflows/create-bundle.yml
    with:
      artifact_type: linux
      platform: Linux
      zip_prefix: linux64

  build-windows:
    needs: [env-setup]
    uses: ./.github/workflows/build-windows-artifact.yml
    with:
      godot_tag: ${{ inputs.godot_tag }}
      mono_tag: ${{ inputs.mono_tag }}
      steamworks_sdk_tag: ${{ inputs.steamworks_sdk_tag }}
    secrets:
      steamworks_sdk_repo: ${{ secrets.STEAMWORKS_SDK_REPO }}
      steamworks_sdk_repo_token: ${{ secrets.STEAMWORKS_SDK_REPO_TOKEN }}

  create-windows32-bundle:
    needs: [env-setup, build-windows]
    uses: ./.github/workflows/create-bundle.yml
    with:
      artifact_type: windows32
      platform: Windows32
      zip_prefix: win32

  create-windows64-bundle:
    needs: [env-setup, build-windows]
    uses: ./.github/workflows/create-bundle.yml
    with:
      artifact_type: windows64
      platform: Windows64
      zip_prefix: win64

  build-macos:
    needs: [env-setup]
    uses: ./.github/workflows/build-macos-artifact.yml
    with:
      godot_tag: ${{ inputs.godot_tag }}
      mono_tag: ${{ inputs.mono_tag }}
      steamworks_sdk_tag: ${{ inputs.steamworks_sdk_tag }}
    secrets:
      steamworks_sdk_repo: ${{ secrets.STEAMWORKS_SDK_REPO }}
      steamworks_sdk_repo_token: ${{ secrets.STEAMWORKS_SDK_REPO_TOKEN }}

  create-macos-bundle:
    needs: [env-setup, build-macos]
    uses: ./.github/workflows/create-bundle.yml
    with:
      artifact_type: macos
      platform: MacOS
      zip_prefix: macos

  create-template-bundle:
    needs: [env-setup, build-linux, build-windows, build-macos]
    uses: ./.github/workflows/create-bundle-templates.yml
    with:
      is_mono: false

  create-mono-template-bundle:
    needs: [env-setup, build-linux, build-macos]
    uses: ./.github/workflows/create-bundle-templates.yml
    with:
      is_mono: true