name: Build Releases
on:
  workflow_dispatch:
    inputs:
      steamworks_sdk_tag:
        description: 'Steamworks SDK Tag:'
        required: true
        type: string
        default: 'sdk-1.57'
      godotsteam_version:
        description: 'GodotSteam GDExtension Tag:'
        required: true
        type: string
        default: '4.2.2-gde'
      release_title:
        description: 'Github Release Title:'
        required: true
        type: string
        default: 'Godot 4.1 - Steamworks 1.57 - GodotSteam GDExtension 4.2.4'

jobs:
  build-gdextension-release:
    uses: ./.github/workflows/build-gdextension.yml
    with:
      steamworks_sdk_tag: ${{ inputs.steamworks_sdk_tag }}
    secrets:
      steamworks_sdk_repo: ${{ secrets.STEAMWORKS_SDK_REPO }}
      steamworks_sdk_repo_token: ${{ secrets.STEAMWORKS_SDK_REPO_TOKEN }}
