on:
  workflow_call:
    inputs:
      godot_tag:
        required: true
        type: string
      godot_version:
        required: true
        type: string
      steamworks_sdk_tag:
        required: true
        type: string
    secrets:
      steamworks_sdk_repo:
        required: true
      steamworks_sdk_repo_token:
        required: true


jobs:
  build-macos:
    runs-on: macos-latest


    name: Mac ${{ matrix.name }}


    env:
      STRIP: "strip -u -r"


    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor and Templates
            cache-name: macos


    steps:
      - uses: actions/checkout@v4

      # Download Godot to start
      - name: Download Godot
        uses: ./.github/actions/download-godot
        with:
          version: ${{ inputs.godot_tag }}

      # Download GodotSteam
      - name: Download GodotSteam
        uses: ./.github/actions/download-godotsteam

      # Download Steamworks SDK
      - name: Download Steamworks SDK
        uses: ./.github/actions/download-steamworks
        with:
          path: "steamworks"
          repository: ${{ secrets.steamworks_sdk_repo }}
          token: ${{ secrets.steamworks_sdk_repo_token }}
          ref: ${{ inputs.steamworks_sdk_tag }}

      # Get that cache money
      - name: Setup Build Cache
        uses: ./.github/actions/setup-cache
        with:
          cache-name: ${{ matrix.cache-name }}
          godot-base: inputs.godot_tag
        continue-on-error: true

      # Setup Python and SCONS
      - name: Setup Python and SCONS
        uses: ./.github/actions/setup-dependencies

      # Compiling editors
      - name: Editor compilation (arch=x86_64)
        uses: ./.github/actions/build-godot
        with:
          sconsflags: arch=x86_64 tools=yes
          platform: osx
          target: release_debug

      - name: Editor Compilation (arch=arm64)
        uses: ./.github/actions/build-godot
        with:
          sconsflags: arch=arm64 tools=yes
          platform: osx
          target: release_debug

      # Create Mac Universal package
      - name: Package Editor (arch=arm64, x86_64)
        run: |
          ls -l bin/
          lipo -create bin/godot.osx.opt.tools.x86_64 bin/godot.osx.opt.tools.arm64 -output bin/godot.osx.editor.universal
          $STRIP bin/godot.osx.editor.universal
          cp -r misc/dist/osx_tools.app bin/GodotSteam.app
          mkdir -p bin/GodotSteam.app/Contents/MacOS
          cp bin/godot.osx.editor.universal bin/GodotSteam.app/Contents/MacOS/GodotSteam
          chmod +x bin/GodotSteam.app/Contents/MacOS/GodotSteam
          ls -l bin/

      - name: Upload Editor
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}-editor
          path: bin/GodotSteam.app

      - name: Clear bin
        run: |
          rm -rf bin

      # Compiling templates
      - name: Debug Template Compilation (arch=x86_64, target=release_debug)
        uses: ./.github/actions/build-godot
        with:
          sconsflags: arch=x86_64 tools=no
          platform: osx
          target: release_debug

      - name: Debug Template Compilation (arch=arm64, target=release_debug)
        uses: ./.github/actions/build-godot
        with:
          sconsflags: arch=arm64 debug_symbols=no tools=no
          platform: osx
          target: release_debug

      - name: Release Template Compilation (arch=x86_64, target=release)
        uses: ./.github/actions/build-godot
        with:
          sconsflags: arch=x86_64 tools=no
          platform: osx
          target: release

      - name: Release template Compilation (arch=arm64, target=release)
        uses: ./.github/actions/build-godot
        with:
          sconsflags: arch=arm64 debug_symbols=no tools=no
          platform: osx
          target: release

      # Create Mac Universal package
      - name: Package Templates (arch=arm64, x86_64)
        run: |
          ls -l bin/
          lipo -create bin/godot.osx.opt.debug.x86_64 bin/godot.osx.opt.debug.arm64 -output bin/godot.osx.template.debug.universal
          $STRIP bin/godot.osx.template.debug.universal
          lipo -create bin/godot.osx.opt.x86_64 bin/godot.osx.opt.arm64 -output bin/godot.osx.template.universal
          $STRIP bin/godot.osx.template.universal
          cp -r misc/dist/osx_template.app bin/
          mkdir -p bin/macos_template.app/Contents/MacOS
          cp bin/godot.osx.template.universal bin/macos_template.app/Contents/MacOS/godot_macos_release.universal
          cp bin/godot.osx.template.debug.universal bin/macos_template.app/Contents/MacOS/godot_macos_debug.universal
          chmod +x bin/macos_template.app/Contents/MacOS/godot_macos*
          zip -q -9 -r bin/macos.zip bin/macos_template.app
          ls -l bin/

      - name: Upload Mac Template App
        uses: ./.github/actions/upload-artifact
        with:
          name: macos-template-app
          path: bin/macos.zip

      - name: Clear bin
        run: |
          rm -rf bin

      # Upload the Steam redistributable for packaging
      - name: Upload Mac Steam File
        uses: ./.github/actions/upload-steam-redistributable
        with:
          name: ${{ matrix.cache-name }}-steam
          path: osx/
          redist: libsteam_api.dylib